global:
  checkNewVersion: true
  sendAnonymousUsage: false

entryPoints:
  web:
    address: :80

  websecure:
    address: :443

log:
  level: DEBUG

api:

  dashboard: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: "web"

certificatesResolvers:
  CFresolver:
    acme:
      email: ssl@swstack.com
      storage: acme.json
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 10
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
      caServer: https://acme-v02.api.letsencrypt.org/directory
